### PR TITLE
Use Cloudflare API Token with scoped permissions in favour of API Key for better security

### PR DESCRIPTION
**Pull request by hlqviet**
The Global API Key can be used to do whatever within an account so it is very risky. The code has been updated to use API Token with backward compatibility for API Key while also warning its usage for existing users.

CLOUDFLARE_ACCOUNT_EMAIL is no longer needed.

Also updated instructions for API Token.

### CODE REVIEW

**Comment by mrrfv** [comment]
Thanks, I'll test and merge this later.

**Comment by hlqviet** [comment]
I tested with 277 lists without fast mode and it took over 6 minutes for the creating lists operation alone. It had moved to the next rate-limiting window by the time it completed the creating lists operation. And it didn't even reach half of the request limit so I think it's safe to remove `sleep`.

**Comment by mrrfv** [comment]
Makes perfect sense now, I was wrong about the sensitivity of the rate-limiting. I tested your PR and it does the job very well - however I'm noticing this weird bug, possibly on Cloudflare's backend, where the server suddenly thinks the API token is invalid for no particular reason (works for about 50 lists, returns a few errors with the message `Authentication error (10000)` then continues as usual). This doesn't seem to happen when a Global API Key is used.
Probably a good idea to simply wait until Cloudflare is truly done restoring their services.

**Comment by hlqviet** [comment]
It seems stable now

image

**Comment by mrrfv** [comment]
It does work nicely now indeed! Again, thanks for the constant stream of improvements; stuff like this rarely happens and is very much appreciated.

**Pull request merged**
