### PR TITLE
Port list download code to JS

### PR DESCRIPTION
**Pull request by hlqviet**
I wish I could remove all the shell scripts but for the sake of compatibility 🥲

### CODE REVIEW

**Comment by mrrfv** [comment]
The names `whitelist.csv` and `input.csv` shouldn't be completely removed for compatibility with older versions (maybe add a fallback?). And I think it'll be a good idea to just go all-in on Node.js for allow/blocklist downloads and replace the contents of `get_recommended_*.sh` with `node [script].js` commands so the lists can be downloaded on any system, including Windows.

**Comment by hlqviet** [comment]
Hmm... Let me revert the name changes then.

**Comment by mrrfv** [comment]
Fair enough. I didn't notice that. There's still a probability that the script's going to break for people using their own lists though.

> Hmm... Let me revert the name changes then.

No need to revert them, just dynamically adjust the name of files being used based on which one exists. You can use `fs.existsSync()` for that.

**Comment by hlqviet** [comment]
So here it is 😁

**Comment by hlqviet** [comment]
May want to add that these scripts support hosts, domain and adblock formats but work best with wildcard domain (without asterisk) format now.

**Comment by mrrfv** [comment]
Thanks! I’m feeling guilty for burdening you with so many requests, but there’s one more tiny thing. Could you please make it so that the download_lists Node script grabs both allowlists and blocklists when it’s run with no arguments? That’d be good for convenience.

**Comment by hlqviet** [comment]
Alright.

**Comment by mrrfv** [comment]
Thanks for contributing so much :)

**Pull request merged**
