### PR TITLE
API request code refactor

### PR DESCRIPTION
**Pull request by hlqviet**
This PR:

- Removes `node-fetch` as `node` is upgraded to the latest LTS version which has native `fetch`
- Moves the environment variables in the workflow out of the jobs
- Separate common functions into utils and helpers
- Adds the ability to fire the API requests simultaneously with `FAST_MODE` environment variable
- Changes how `DRY_RUN` is handled (`"true"` or empty to `0` or `1`)

This is based on the branch from #19 so should be reviewed after that PR.

### CODE REVIEW

**Comment by sntran** [comment]
> Moves the environment variables in the workflow out of the jobs

May not want to do this as we don't want the environment variables available during `npm ci`. Some bad packages may be able to read them.

**Comment by hlqviet** [comment]
> > Moves the environment variables in the workflow out of the jobs
> 
> May not want to do this as we don't want the environment variables available during `npm ci`. Some bad packages may be able to read them.

Doesn't look like it can happen with this only package but yeah can't be wrong.

**Comment by mrrfv** [comment]
I'm not sure about completely removing `node-fetch` to be honest. The current GitHub Actions workflow uses Node.js 16 which (I think?) doesn't support native `fetch` - so in order to retain backwards compatibility, this update (and subsequent changes) would have to be pushed to a `v2` branch. Is there any way for `node-fetch` to maybe be installed when it's needed?

**Comment by hlqviet** [comment]
> Is there any way for `node-fetch` to maybe be installed when it's needed?

Without touching workflow file I'm afraid no. Maybe we will maintain both `v1` and `v2` so both will have all the enhancements with the only difference on `node-fetch`. That way existing users will still have the benefits.

**Comment by hlqviet** [comment]
One more suggested way is to keep `node-fetch` but use it conditionally by checking if there is native `fetch` before importing it.

**Comment by mrrfv** [comment]
Looks good now, thanks!

**Pull request merged**
