### PR TITLE
Domain process code refactor

### PR DESCRIPTION
**Pull request by hlqviet**
- Set `NODE_ENV` to `production` to ensure everything runs in an optimal state
References:
  - https://nodejs.dev/en/learn/nodejs-the-difference-between-development-and-production/
  - https://www.dynatrace.com/news/blog/the-drastic-effects-of-omitting-node-env-in-your-express-js-applications/
- Refactored domain processing code:
  - Go through each list only once
  - Prevent adding a subdomain to the blocklist if a higher-level one is already blocked
  - Stop processing blocklist once the number of blocked domains reached
  - Use `Map` for best lookup performance
 References:
    - https://stackoverflow.com/a/62351925
    - https://stackoverflow.com/a/66932877
- Cleaned up a few other pieces of code

### CODE REVIEW

**Comment by hlqviet** [comment]
Results after 0833352

image

image

=> 94 lists reduced

**Comment by hlqviet** [comment]
Hi @mrrfv. Can you take a look?

**Comment by mrrfv** [comment]
Yes, sorry for the wait. Could you please add more comments to the code (describing what does a specific line do, what is anyDomainExists or an unnecessary domain, etc)? The current version is a bit hard to understand at first glance.

**Comment by hlqviet** [comment]
> Yes, sorry for the wait. Could you please add more comments to the code (describing what does a specific line do, what is anyDomainExists or an unnecessary domain, etc)? The current version is a bit hard to understand at first glance.

Sure. I just added a few comments to explain the code.

**Comment by mrrfv** [comment]
Looks good now, thanks.

**Pull request merged**
